DECLARE
   CURSOR C_SERVICE IS
     SELECT EMPID, EMPNAME,JOINING_DATE,RELIEVING_DATE FROM EMPLOYEE WHERE RELIEVING_DATE IS NOT NULL;
   VEMPID EMPLOYEE.EMPID%TYPE;
   VEMPNAME EMPLOYEE.EMPNAME%TYPE;
   VJOINING_DATE EMPLOYEE.JOINING_DATE%TYPE;
   VRELIEVING_DATE EMPLOYEE.RELIEVING_DATE%TYPE;
   VSERVICE NUMBER;
BEGIN
   OPEN C_SERVICE;
   LOOP
   FETCH C_SERVICE INTO VEMPID,VEMPNAME,VJOINING_DATE,VRELIEVING_DATE;
   EXIT WHEN C_SERVICE%NOTFOUND;

   VSERVICE := TRUNC(MONTHS_BETWEEN(VRELIEVING_DATE,VJOINING_DATE)/12);
   DBMS_OUTPUT.PUT_LINE('Employee: ' || VEMPNAME || ' | Service (years): ' || VSERVICE);
   END LOOP;
CLOSE C_SERVICE;
END;
/