DECLARE
   CURSOR C_PERSON IS
        SELECT PID,PNAME,DOB FROM PERSON;
   VPID  PERSON.PID%TYPE;
   VPNAME  PERSON.PNAME%TYPE;
   VDOB  PERSON.DOB%TYPE;
   VAGE  NUMBER;
BEGIN
   OPEN C_PERSON;
   LOOP
      FETCH C_PERSON INTO VPID,VPNAME,VDOB;
      EXIT WHEN C_PERSON%NOTFOUND;

      VAGE := TRUNC(MONTHS_BETWEEN(SYSDATE,vDOB)/12);

      DBMS_OUTPUT.PUT_LINE('PID' || VPID||', NAME '||VPNAME||', AGE '|| VAGE);
    END LOOP;
    CLOSE C_PERSON;
END;
/