DECLARE
   CURSOR C_PENSION IS SELECT EMPID, EMPNAME,JOINING_DATE,RELIEVING_DATE,SALARY FROM EMPLOYEE WHERE RELIEVING_DATE IS NOT NULL;
   VEMPID EMPLOYEE.EMPID%TYPE;
   VEMPNAME EMPLOYEE.EMPNAME%TYPE;
   VJOINING_DATE EMPLOYEE.JOINING_DATE%TYPE;
   VRELIEVING_DATE EMPLOYEE.RELIEVING_DATE%TYPE;
   VSAL EMPLOYEE.SALARY%TYPE;
   VSERVICE NUMBER;
   VPENSION NUMBER;

BEGIN
   OPEN C_PENSION;
   LOOP
       FETCH C_PENSION INTO VEMPID,VEMPNAME,VJOINING_DATE,VRELIEVING_DATE,VSAL;
       EXIT WHEN C_PENSION%NOTFOUND;

       VSERVICE:= TRUNC(MONTHS_BETWEEN(VRELIEVING_DATE,VJOINING_DATE)/12);
       VPENSION := (VSAL*VSERVICE)/100;
       DBMS_OUTPUT.PUT_LINE('Employee: ' || VEMPNAME || ' | pENSION: ' || VPENSION);
   END LOOP;
CLOSE C_PENSION;
END;
/