DECLARE
   STR VARCHAR2(10) := '&STR';
   REV VARCHAR2(10) := '';
   I NUMBER;
BEGIN
   FOR I IN REVERSE 1..LENGTH(STR) LOOP
      REV := REV || SUBSTR(STR,I,1);
   END LOOP;

   IF LOWER(STR) = LOWER(REV) THEN
      DBMS_OUTPUT.PUT_LINE(STR || ' IS PALINDROME');
   ELSE
      DBMS_OUTPUT.PUT_LINE(STR || ' IS NOT PALINDROME');
   END IF;
END;
/