CREATE OR REPLACE TRIGGER INC_UPDATE
AFTER UPDATE OF SALARY
ON EMPLOYEE
FOR EACH ROW
DECLARE
  DIF NUMBER;
BEGIN
   DIF := :NEW.SALARY - :OLD.SALARY;

   IF DIF > 1000 THEN
      INSERT INTO INCREMENTS VALUES(:NEW.EMPID, DIF);
      DBMS_OUTPUT.PUT_LINE('INCREMENT RECORDED FOR: ' || :NEW.EMPID || ' INCREASE ' || DIF);
   END IF;
END;
/
