CREATE OR REPLACE TRIGGER E_COUNT
AFTER INSERT OR DELETE OR UPDATE
ON EMPLOYEE
DECLARE
   ECOUNT NUMBER;
BEGIN
   SELECT COUNT(*) INTO ECOUNT FROM EMPLOYEE;
   DBMS_OUTPUT.PUT_LINE('EMPLOYEE COUNT : '|| ECOUNT);
END;
/